import Header from "@/components/layouts/header"
import AboutSection from "@/components/sections/contact/contact"
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";
import ContactSection from "@/components/sections/contact/contact";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <ContactSection />
      <Footer />

    </main>
  )
}