import Header from "@/components/layouts/header"
import BlogsSection from "@/components/sections/blogs/blogs"
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "News & Blogs",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <BlogsSection />
      <Footer />

    </main>
  )
}