import Header from "@/components/layouts/header"
import AboutSection from "@/components/sections/about/about"
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />

      <Footer />

    </main>
  )
}