import Header from "@/components/layouts/header"
import ProductSection from "@/components/sections/product/product"
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "List Product",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <ProductSection/>
      <Footer />

    </main>
  )
}