import Header from "@/components/layouts/header"
import ProductSection from "@/components/sections/product/product"
import Footer from "@/components/layouts/footer"
import { prisma } from "@/lib/prisma"
import type { Metadata } from "next";

export const dynamic = "force-dynamic"

export const metadata: Metadata = {
  title: "List Product",
  description: "Generated by create next app",
};

export default async function ProductPage() {
  const categories = await prisma.category.findMany({
    include: { products: true },
    orderBy: { name: "asc" },
  })

  return (
    <main>
      <Header />
      <ProductSection categories={categories} />
      <Footer />
    </main>
  )
}
